name: Duels
version: 1.0.0
api: ["4.0.0"]
main: duels\Loader
author: ["Skyder", "FaizDev"]

website: https://github.com/SkyderG/Duels

commands:
  duels:
    description: Duel plugin management.
    permission: duels.usage
    aliases:
      - duel
      - 1vs1

permissions:
  duels.usage:
    default: op